name: villaguest
description: ""
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

  # Estado y manejo de datos
  provider: ^6.1.1               # Gestión de estado simple (o riverpod si prefieres)
  equatable: ^2.0.5              # Facilita comparaciones
  json_annotation: ^4.8.1        # Para serialización de modelos

  # Calendario
  timetide: ^1.2.1            # El más completo

  # Pagos (Stripe)
  flutter_stripe: ^10.0.0        # SDK nativo de Stripe para Flutter

  # Comunicación (WhatsApp API)
  whatsapp_cloud_flutter: ^1.0.0 # No oficial pero útil

  # Utilidades
  intl: ^0.18.1                  # Formateo de fechas y monedas
  image_picker: ^1.0.5           # Para cámara/fotos (limpieza)
  qr_flutter: ^4.1.0             # Generador de códigos QR
  url_launcher: ^6.2.1           # Abrir enlaces, WhatsApp, etc.
  flutter_dotenv: ^5.1.0         # Variables de entorno (.env)

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7           # Para generar código (json_serializable)
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
