// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT8Cx-Giwzish8zD7uhoMtpnqtTGzjwqE',
    appId: '1:55453466052:web:280cb6d03107737a8a3891',
    messagingSenderId: '55453466052',
    projectId: 'villaguest-bc616',
    authDomain: 'villaguest-bc616.firebaseapp.com',
    storageBucket: 'villaguest-bc616.firebasestorage.app',
    measurementId: 'G-JVCVVB18PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgWM1CryseKcfC3PaVivsULcToa9-vtgE',
    appId: '1:55453466052:android:e9570aef7fc7ad818a3891',
    messagingSenderId: '55453466052',
    projectId: 'villaguest-bc616',
    storageBucket: 'villaguest-bc616.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv4MDeQm-nG8bd4bh0WNTutw6uLXkbC7M',
    appId: '1:55453466052:ios:14d0d3787ed440b38a3891',
    messagingSenderId: '55453466052',
    projectId: 'villaguest-bc616',
    storageBucket: 'villaguest-bc616.firebasestorage.app',
    iosBundleId: 'com.example.villaguest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv4MDeQm-nG8bd4bh0WNTutw6uLXkbC7M',
    appId: '1:55453466052:ios:14d0d3787ed440b38a3891',
    messagingSenderId: '55453466052',
    projectId: 'villaguest-bc616',
    storageBucket: 'villaguest-bc616.firebasestorage.app',
    iosBundleId: 'com.example.villaguest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT8Cx-Giwzish8zD7uhoMtpnqtTGzjwqE',
    appId: '1:55453466052:web:6801f509c80bd88a8a3891',
    messagingSenderId: '55453466052',
    projectId: 'villaguest-bc616',
    authDomain: 'villaguest-bc616.firebaseapp.com',
    storageBucket: 'villaguest-bc616.firebasestorage.app',
    measurementId: 'G-ZTWRCWS5GZ',
  );
}
